//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosterForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Line
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Line()
        {
            this.File = new HashSet<File>();
        }
    
        public int Id { get; set; }
        public int PaperTypeId { get; set; }
        public string PaperTypeName { get; set; }
        public decimal PaperCost { get; set; }
        public decimal PaperWidth { get; set; }
        public decimal PaperHeight { get; set; }
        public int PaperUnits { get; set; }
        public decimal ItemUnits { get; set; }
        public int NumLam { get; set; }
        public int PaperGrommet { get; set; }
        public int NumBoards { get; set; }
        public decimal LineSubtotal { get; set; }
        public int OrderId { get; set; }
        public int NumFrame { get; set; }
        public int NumRhyno { get; set; }
        public int NumTubes { get; set; }
        public decimal CuttingFee { get; set; }
        public int NumLamMatte { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<File> File { get; set; }
        public virtual Order Order { get; set; }
    }
}
