//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosterForm.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.ModelConfiguration.Conventions;

    public partial class PosterFormConnectionEntities : DbContext
    {
        public PosterFormConnectionEntities()
            : base("name=PosterFormConnectionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Conventions.Remove<PluralizingTableNameConvention>();
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<File> File { get; set; }
        public virtual DbSet<Finishing> Finishing { get; set; }
        public virtual DbSet<Line> Line { get; set; }
        public virtual DbSet<Note> Note { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<OrderPack> OrderPack { get; set; }
        public virtual DbSet<PaperType> PaperType { get; set; }
        public virtual DbSet<UserInRole> UserInRole { get; set; }
    }
}
